export const dummyBooks = [
  {
    id: "1",
    title: "The Alchemist",
    description: "A journey of self-discovery and following your dreams.",
    price: 199,
    image: "https://covers.openlibrary.org/b/id/8278325-L.jpg",
    author: "Paulo Coelho",
    genre: "Fiction",
    location: "Delhi",
    owner: "Amit Sharma",
    isRented: false,
    listingType: "rent",
  },
  {
    id: "2",
    title: "Atomic Habits",
    description:
      "An easy & proven way to build good habits and break bad ones.",
    price: 250,
    image:
      "https://images.unsplash.com/photo-1586489948400-70654c6f342e?auto=format&fit=crop&w=400&q=80",
    author: "Paulo Coelho",
    genre: "Horror",
    location: "Delhi",
    owner: "Amit Sharma",
    isRented: false,
    listingType: "exchange",
  },
//   {
//     id: 3,
//     title: "Rich Dad Poor Dad",
//     description:
//       "What the rich teach their kids about money that the poor do not.",
//     price: 180,
//     image: "https://covers.openlibrary.org/b/id/10958352-L.jpg",
//     author: "Paulo Coelho",
//     genre: "Fiction",
//     location: "Delhi",
//     owner: "Amit Sharma",
//     isRented: true,
//   },
//   {
//     id: 4,
//     title: "1984",
//     description:
//       "A dystopian social science fiction novel and cautionary tale.",
//     price: 160,
//     image: "https://covers.openlibrary.org/b/id/11153266-L.jpg",
//     author: "Paulo Coelho",
//     genre: "Fiction",
//     location: "Delhi",
//     owner: "Amit Sharma",
//     isRented: false,
//   },
//   {
//     id: 5,
//     title: "The Subtle Art of Not Giving a F*ck",
//     description: "A counterintuitive approach to living a good life.",
//     price: 210,
//     image: "https://covers.openlibrary.org/b/id/8372795-L.jpg",
//     author: "Paulo Coelho",
//     genre: "Fiction",
//     location: "Delhi",
//     owner: "Amit Sharma",
//     isRented: false,
//   },
//   {
//     id: 6,
//     title: "To Kill a Mockingbird",
//     description:
//       "A novel about the serious issues of rape and racial inequality.",
//     price: 190,
//     image: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
//     author: "Paulo Coelho",
//     genre: "Fiction",
//     location: "Delhi",
//     owner: "Amit Sharma",
//     isRented: true,
//   },
];
